import { launch, boot, snap, pos, walkTo, clickTile, pickTool, press, winOpen, winTitle, lastToast } from "./harness.mjs";
const { browser, page, errors } = await launch();
await boot(page, { fresh: true });
await page.waitForTimeout(300);
await walkTo(page, 7, 9);
await page.evaluate(() => { window.__MOSS__.state.energy = 1; });
await pickTool(page, 1); await clickTile(page, 7, 8);
console.log("A toast", await lastToast(page), "energy", (await snap(page)).energy, "plots", Object.keys((await snap(page)).plots));
await page.keyboard.down("ArrowLeft"); await page.waitForTimeout(300); await page.keyboard.up("ArrowLeft");
console.log("B pos", await pos(page));
await page.evaluate(() => { const s = window.__MOSS__.state; s.energy = 20; s.inventory.radish = 1; });
console.log("C walkTo", await walkTo(page, 7, 9), await pos(page));
await pickTool(page, 1); await clickTile(page, 7, 8);
console.log("D toast", await lastToast(page), "plots", Object.keys((await snap(page)).plots));
await pickTool(page, 2); await clickTile(page, 7, 8);
console.log("E toast", await lastToast(page), "plots", JSON.stringify((await snap(page)).plots));
await page.evaluate(() => { const s = window.__MOSS__.state; s.energy = 1; s.plots["7,8"].mature = true; s.inventory.radish = 1; });
await press(page, "b");
await page.waitForTimeout(300);
console.log("F winOpen", await winOpen(page), "active", await page.evaluate(()=>document.activeElement.tagName+"#"+document.activeElement.className));
console.log("G items", await page.evaluate(()=>[...document.querySelectorAll(".win .item")].map(n=>n.innerText.replace(/\n/g,"|"))));
console.log("errors", errors);
await browser.close();
