import { launch, boot, snap, pos, walkTo, clickTile, pickTool, faceTowards, lastToast, winOpen, winTitle } from "./harness.mjs";
const { browser, page, errors } = await launch();
await boot(page, { fresh: true });
await walkTo(page, 3, 5);
await page.keyboard.press("e"); await page.waitForTimeout(700);
console.log("scene", (await snap(page)).scene, "pos", await pos(page));
console.log("walkTo(2,3):", await walkTo(page, 2, 3), "pos", await pos(page));
await pickTool(page, 1);
console.log("tool", await page.evaluate(()=>window.__MOSS__.state.selectedTool));
const pt = await page.evaluate(()=>window.__MOSS__.tileToScreen(2,2));
console.log("tileToScreen(2,2)", pt, "canvasRect", await page.evaluate(()=>window.__MOSS__.canvasRect));
await page.mouse.click(pt[0], pt[1]);
await page.waitForTimeout(300);
console.log("toast:", await lastToast(page));
console.log("hoverTile:", await page.evaluate(()=>JSON.stringify(window.__MOSS__.game.hoverTile)));
console.log("selectTile:", await page.evaluate(()=>JSON.stringify(window.__MOSS__.game.selectTile)));
console.log("toasts:", await page.evaluate(()=>JSON.stringify(window.__MOSS__.toasts.slice(-4))));
console.log("errors", errors);
await browser.close();
