import { launch, boot, snap, pos } from "./harness.mjs";
const { browser, page, errors } = await launch();
await boot(page, { fresh: true });
await page.waitForTimeout(300);
await page.evaluate(()=>{ const M=window.__MOSS__; M.state.player={x:27,y:16,face:"down"}; M.game.ppos.x=27*16+8; M.game.ppos.y=16*16+12; M.saveNow(); });
await page.waitForTimeout(600);
const snap1 = await page.evaluate(()=>{ const f=window.__MOSS__.game.pondFish; return f ? f.map(x=>({x:Math.round(x.x),y:Math.round(x.y),d:x.dir})) : null; });
console.log("fish count:", snap1 ? snap1.length : "none");
console.log("t0:", JSON.stringify(snap1));
await page.waitForTimeout(3000);
const snap2 = await page.evaluate(()=>{ const f=window.__MOSS__.game.pondFish; return f.map(x=>({x:Math.round(x.x),y:Math.round(x.y),d:x.dir})); });
console.log("t3:", JSON.stringify(snap2));
const moved = snap1.filter((f,i)=>Math.abs(f.x-snap2[i].x)>3).length;
console.log("moved fish:", moved, "/", snap1.length);
const outOfWater = snap2.filter(f => { const tx=Math.floor(f.x/16), ty=Math.floor(f.y/16); return !(tx>=26&&tx<=30&&ty>=17&&ty<=21); });
console.log("out of water:", JSON.stringify(outOfWater));
const r = await page.evaluate(()=>{ const b=document.getElementById("viewport").getBoundingClientRect(); return {l:b.left,t:b.top,w:b.width,h:b.height}; });
await page.screenshot({ path: "../output/playwright/v3-pond.png", clip:{ x:r.l, y:r.t+ (14*16/256)*r.h, width:r.w, height:(7*16/256)*r.h } });
await page.screenshot({ path: "../output/playwright/v3-pond-full.png" });
console.log("errors:", errors);
await browser.close();
